/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDiagnosesRouteImport } from './routes/_authenticated/diagnoses'
import { Route as AuthenticatedDiagnosesIndexRouteImport } from './routes/_authenticated/diagnoses.index'
import { Route as AuthenticatedDiagnosesNewRouteImport } from './routes/_authenticated/diagnoses.new'
import { Route as AuthenticatedDiagnosesIdRouteImport } from './routes/_authenticated/diagnoses.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiagnosesRoute = AuthenticatedDiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosesIndexRoute =
  AuthenticatedDiagnosesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDiagnosesRoute,
  } as any)
const AuthenticatedDiagnosesNewRoute =
  AuthenticatedDiagnosesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDiagnosesRoute,
  } as any)
const AuthenticatedDiagnosesIdRoute =
  AuthenticatedDiagnosesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDiagnosesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/diagnoses': typeof AuthenticatedDiagnosesRouteWithChildren
  '/diagnoses/$id': typeof AuthenticatedDiagnosesIdRoute
  '/diagnoses/new': typeof AuthenticatedDiagnosesNewRoute
  '/diagnoses/': typeof AuthenticatedDiagnosesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/diagnoses/$id': typeof AuthenticatedDiagnosesIdRoute
  '/diagnoses/new': typeof AuthenticatedDiagnosesNewRoute
  '/diagnoses': typeof AuthenticatedDiagnosesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/diagnoses': typeof AuthenticatedDiagnosesRouteWithChildren
  '/_authenticated/diagnoses/$id': typeof AuthenticatedDiagnosesIdRoute
  '/_authenticated/diagnoses/new': typeof AuthenticatedDiagnosesNewRoute
  '/_authenticated/diagnoses/': typeof AuthenticatedDiagnosesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/diagnoses'
    | '/diagnoses/$id'
    | '/diagnoses/new'
    | '/diagnoses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/diagnoses/$id' | '/diagnoses/new' | '/diagnoses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/diagnoses'
    | '/_authenticated/diagnoses/$id'
    | '/_authenticated/diagnoses/new'
    | '/_authenticated/diagnoses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/diagnoses': {
      id: '/_authenticated/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof AuthenticatedDiagnosesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnoses/': {
      id: '/_authenticated/diagnoses/'
      path: '/'
      fullPath: '/diagnoses/'
      preLoaderRoute: typeof AuthenticatedDiagnosesIndexRouteImport
      parentRoute: typeof AuthenticatedDiagnosesRoute
    }
    '/_authenticated/diagnoses/new': {
      id: '/_authenticated/diagnoses/new'
      path: '/new'
      fullPath: '/diagnoses/new'
      preLoaderRoute: typeof AuthenticatedDiagnosesNewRouteImport
      parentRoute: typeof AuthenticatedDiagnosesRoute
    }
    '/_authenticated/diagnoses/$id': {
      id: '/_authenticated/diagnoses/$id'
      path: '/$id'
      fullPath: '/diagnoses/$id'
      preLoaderRoute: typeof AuthenticatedDiagnosesIdRouteImport
      parentRoute: typeof AuthenticatedDiagnosesRoute
    }
  }
}

interface AuthenticatedDiagnosesRouteChildren {
  AuthenticatedDiagnosesIdRoute: typeof AuthenticatedDiagnosesIdRoute
  AuthenticatedDiagnosesNewRoute: typeof AuthenticatedDiagnosesNewRoute
  AuthenticatedDiagnosesIndexRoute: typeof AuthenticatedDiagnosesIndexRoute
}

const AuthenticatedDiagnosesRouteChildren: AuthenticatedDiagnosesRouteChildren =
  {
    AuthenticatedDiagnosesIdRoute: AuthenticatedDiagnosesIdRoute,
    AuthenticatedDiagnosesNewRoute: AuthenticatedDiagnosesNewRoute,
    AuthenticatedDiagnosesIndexRoute: AuthenticatedDiagnosesIndexRoute,
  }

const AuthenticatedDiagnosesRouteWithChildren =
  AuthenticatedDiagnosesRoute._addFileChildren(
    AuthenticatedDiagnosesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDiagnosesRoute: typeof AuthenticatedDiagnosesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDiagnosesRoute: AuthenticatedDiagnosesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
